import { genId } from "./utils";

const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();

export function buildSeedLeads() {
  return [
    {
      id: genId(),
      name: "Priya Nakamura",
      company: "Northwind Logistics",
      email: "priya@northwindlog.com",
      phone: "555-0142",
      value: 18000,
      stage: "proposal",
      source: "Referral",
      notes: "Wants a demo of the reporting module before signing.",
      createdAt: daysAgo(21),
      updatedAt: daysAgo(2),
    },
    {
      id: genId(),
      name: "Daniel Osei",
      company: "Brightline Retail",
      email: "daniel@brightlineretail.com",
      phone: "555-0188",
      value: 7200,
      stage: "contacted",
      source: "Website",
      notes: "Follow up after their Q3 budget is approved.",
      createdAt: daysAgo(14),
      updatedAt: daysAgo(5),
    },
    {
      id: genId(),
      name: "Maren Solberg",
      company: "Fjord & Co",
      email: "maren@fjordco.no",
      phone: "555-0116",
      value: 42000,
      stage: "won",
      source: "Partner",
      notes: "Closed on annual plan, upsell opportunity next renewal.",
      createdAt: daysAgo(40),
      updatedAt: daysAgo(1),
    },
    {
      id: genId(),
      name: "Tomás Vega",
      company: "Vega Studio",
      email: "tomas@vegastudio.io",
      phone: "555-0170",
      value: 3200,
      stage: "new",
      source: "Social Media",
      notes: "",
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: genId(),
      name: "Aisha Bello",
      company: "Bello & Partners",
      email: "aisha@bellopartners.com",
      phone: "555-0199",
      value: 15500,
      stage: "qualified",
      source: "Event",
      notes: "Met at SaaSCon, very interested in the team plan.",
      createdAt: daysAgo(9),
      updatedAt: daysAgo(3),
    },
    {
      id: genId(),
      name: "Ethan Cole",
      company: "Cole Manufacturing",
      email: "ethan@colemfg.com",
      phone: "555-0155",
      value: 9800,
      stage: "lost",
      source: "Cold Outreach",
      notes: "Went with a competitor on price.",
      createdAt: daysAgo(30),
      updatedAt: daysAgo(10),
    },
    {
      id: genId(),
      name: "Sofia Marchetti",
      company: "Marchetti Design",
      email: "sofia@marchettidesign.com",
      phone: "555-0133",
      value: 5400,
      stage: "new",
      source: "Referral",
      notes: "",
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    },
    {
      id: genId(),
      name: "Liam O'Connell",
      company: "O'Connell & Sons",
      email: "liam@oconnellsons.ie",
      phone: "555-0121",
      value: 26000,
      stage: "proposal",
      source: "Website",
      notes: "Sent proposal v2 with revised pricing tiers.",
      createdAt: daysAgo(18),
      updatedAt: daysAgo(4),
    },
  ];
}
